image: debian:latest

stages:
  - build
  - test
  - lint

before_script:
  - echo "vvv BEFORE vvv"
  - date
  - apt-get update  -qqy >/dev/null
  - apt-get upgrade -qqy >/dev/null
  - apt-get install -qqy apt-utils >/dev/null
  - apt-get install -qqy tree procps psmisc rsyslog mysql-client libmariadbclient-dev git >/dev/null
  - apt-get install -qqy python3 build-essential python3-dev python3-pip >/dev/null
  - pip3 install -r requirements.txt
  - service rsyslog start
  - ps aux

build_main:
  stage: build
  script:
    - echo "*** BUILD START ***"
    - pushd ..
    - git clone https://gitlab.com/mausy5043-installer/mausy5043-common-python.git
    - pushd mausy5043-common-python
    - ./setup.py install
    - popd
    - popd
    - tree -dL 3 ../..
    - echo "*** BUILD COMPLETE ***"

lint_python:
  stage: lint
  script:
    - pip3 install pylama pylint pycodestyle pydocstyle
    - pylama --skip="build/*" --ignore=C901,E111,E114,E221,E501
    - pycodestyle --ignore=C901,E111,E114,E121,E123,E126,E133,E221,E226,E241,E242,E501,E704,W503,W504,W505 .
    - pylint --rcfile=.pylintrc *.py
    - pydocstyle *

lint_shellcheck-main:
  stage: lint
  script:
    - apt-get install -qqy shellcheck >/dev/null
    - shellcheck --format=gcc --external-sources *.sh

lint_shellcheck-queries:
  stage: lint
  script:
    - apt-get install -qqy shellcheck >/dev/null
    - shellcheck --format=gcc --external-sources queries/*.sh
