image: debian:latest

stages:
  - build
  - test
  - lint

before_script:
  - echo "vvv BEFORE vvv"
  - date
  - apt-get update  -qqy >/dev/null
  - apt-get upgrade -qqy >/dev/null
  - apt-get install -qqy apt-utils
  - apt-get install -qqy tree procps psmisc rsyslog mysql-client libmariadbclient-dev git >/dev/null
  - apt-get install -qqy python3 build-essential python3-dev python3-pip >/dev/null
  - pip3 install -r requirements.txt
  - service rsyslog start
  - ps aux

build_main:
  stage: build
  script:
    - echo "*** BUILD START ***"
    - cd ..
    - git clone https://gitlab.com/mausy5043-installer/mausy5043-common-python.git
    - cd mausy5043-common-python
    - ./setup.py install
    - cd ../upsdiagd
    - tree -dL 3 ../..
    - echo "*** BUILD COMPLETE ***"

lint_pylama:
  stage: lint
  script:
    - pip3 install pylama >/dev/null
    - pylama --skip="build/*" --ignore=E111,E221,E114,E501,C901

lint_shellcheck-main:
  stage: lint
  script:
    - apt-get install -qqy shellcheck >/dev/null
    - shellcheck --format=gcc --external-sources *.sh


lint_shellcheck-queries:
  stage: lint
  script:
    - apt-get install -qqy shellcheck >/dev/null
    - shellcheck --format=gcc --external-sources queries/*.sh
